### ISSUE TITLE
Cannot find cml lab file when trying to build lab

### ISSUE THREAD

**Issue by bluealein56** [CiscoDevNet/ansible-cml#9]
---
- name: Create the lab
  vars: 
    ansible_python_interpreter: python
  cisco.cml.cml_lab:
    host: "{{ inventory_hostname }}"
    user: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    lab: "{{ cml_lab }}"
    state: present
    file: 'roles/build_lab/files/equinix_chicago.yml'
    validate_certs: no
  delegate_to: localhost
  register: results
...

(cml) [toweradmin@lpcdd000 cml_toolbox]$ ansible-playbook playbooks/build_lab.yml -i inventory.yml -k -e cml_lab=Equinix_Atlantas -u cml -vvv
ansible-playbook 2.10.16
  config file = /home/toweradmin/cml_toolbox/ansible.cfg
  configured module search path = ['/home/toweradmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/cml/lib64/python3.6/site-packages/ansible
  executable location = /opt/my-envs/cml/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /home/toweradmin/cml_toolbox/ansible.cfg as config file
SSH password:
host_list declined parsing /home/toweradmin/cml_toolbox/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/toweradmin/cml_toolbox/inventory.yml as it did not pass its verify_file() method
Parsed /home/toweradmin/cml_toolbox/inventory.yml inventory source with yaml plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: build_lab.yml *****************************************************************************************************************************************
1 plays in playbooks/build_lab.yml

PLAY [all] ******************************************************************************************************************************************************
META: ran handlers

TASK [build_lab : Create the lab] *******************************************************************************************************************************
task path: /home/toweradmin/cml_toolbox/roles/build_lab/tasks/main.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: toweradmin
<localhost> EXEC /bin/sh -c 'echo ~toweradmin && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/toweradmin/.ansible/tmp `"&& mkdir "` echo /home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071 `" && echo ansible-tmp-1639153740.8928497-24900-68429571153071="` echo /home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071 `" ) && sleep 0'
Using module file /home/toweradmin/.ansible/collections/ansible_collections/cisco/cml/plugins/modules/cml_lab.py
<localhost> PUT /home/toweradmin/.ansible/tmp/ansible-local-24885f_vcaig0/tmpd_lb64ud TO /home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071/AnsiballZ_cml_lab.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071/ /home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071/AnsiballZ_cml_lab.py && sleep 0'
<localhost> EXEC /bin/sh -c 'python /home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071/AnsiballZ_cml_lab.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071/ > /dev/null 2>&1 && sleep 0'
fatal: [cml1.depot.com -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "SSL Verification disabled\nPlease ensure the client version is compatible with the server version. client 2.1.0, server 2.2.3+build63\nTraceback (most recent call last):\n  File \"/home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071/AnsiballZ_cml_lab.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071/AnsiballZ_cml_lab.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/toweradmin/.ansible/tmp/ansible-tmp-1639153740.8928497-24900-68429571153071/AnsiballZ_cml_lab.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.cml.plugins.modules.cml_lab', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.cml.cml_lab_payload_jq3nzyqh/ansible_cisco.cml.cml_lab_payload.zip/ansible_collections/cisco/cml/plugins/modules/cml_lab.py\", line 144, in <module>\n  File \"/tmp/ansible_cisco.cml.cml_lab_payload_jq3nzyqh/ansible_cisco.cml.cml_lab_payload.zip/ansible_collections/cisco/cml/plugins/modules/cml_lab.py\", line 140, in main\n  File \"/tmp/ansible_cisco.cml.cml_lab_payload_jq3nzyqh/ansible_cisco.cml.cml_lab_payload.zip/ansible_collections/cisco/cml/plugins/modules/cml_lab.py\", line 112, in run_module\n  File \"/opt/my-envs/cml/lib64/python3.6/site-packages/virl2_client/virl2_client.py\", line 442, in import_lab_from_path\n    raise Exception(message)\nException: roles/build_lab/files/equinix_chicago.yml can not be found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ******************************************************************************************************************************************************
cml1.depot.com         : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by edjacks** [comment]
"Our file path is correct and it works if the lab already exists, its only with new lap topologies." - from the individual testing the playbook.

**Comment by djdanielsson** [comment]
If I were to guess it is erroring for another reason but the way the handling of the errors is working out it is printing out that it cannot find the file which isn't actually the case

**Comment by stevenca** [comment]
cml_lab will now prepend the CWD to relative file names.  This means that all relative files will be referenced from the directory from which  ansible-playbook is run.
